# Copyright 2021 Google LLC
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
# Playbook to create Anthos Cluster
- hosts: all
  remote_user: "{{ login_user }}"
  gather_facts: "no"
  vars_files:
    - vars/anthos_vars.yml
  roles:
    - role: ubuntu-prereq
      become: yes
      become_method: sudo
      when: os_type == "ubuntu"
    - role: rhel-prereq
      become: yes
      become_method: sudo
      when: os_type == "rhel"

- hosts: workstation
  remote_user: "{{ login_user }}"
  gather_facts: "no"
  vars_files:
    - vars/anthos_vars.yml
  roles:
    - role: ws-docker
      become: yes
      become_method: sudo
      when: ws_docker == "yes"
    - role: gcloud-sdk
      become: yes
      become_method: sudo
      when: gcloud_sdk == "yes"
    - role: kubectl-tool
      become: yes
      become_method: sudo
      when: kubectl_tool == "yes"
    - role: bmctl-tool
      become: yes
      become_method: sudo
      when: bmctl_tool == "yes"
    - role: service-accounts
      when: service_accounts == "yes"
    - role: anthos
    - role: connect-gateway
      when: (cgw_members is defined) and (cgw_members != None)